name: Greetings

on: [pull_request_target, issues]

jobs:
  greeting:
    runs-on: ubuntu-latest
    permissions:
      issues: write
      pull-requests: write
    steps:
    - uses: actions/first-interaction@v1
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
        issue-message: "Hey Thanks for creating this issue!!!I will look into it and assign it to you if necessary!!!!"
        pr-message: "Hey Thanks for creating this PR!!!I will look into it and merge it, if necessary!!!!"
